apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: vmware/user:1.1
        ports:
          - containerPort: 8080
        resources:
          requests:
            cpu: "0.2"
            memory: 300Mi
          limits:
            cpu: "1.0"
            memory: 300Mi
        readinessProbe:
          httpGet:
            port: 8080
            path: /actuator/health
          initialDelaySeconds: 60
          timeoutSeconds: 2
          periodSeconds: 20
          failureThreshold: 5
        livenessProbe:
          httpGet:
            port: 8080
            path: /actuator/info
          initialDelaySeconds: 60
          timeoutSeconds: 2
          periodSeconds: 20
          failureThreshold: 5
        volumeMounts:
          - name: mongodb
            mountPath: /etc/secretspot
#          - name: config
#            mountPath: /etc/appconfig
      volumes:
        - name: mongodb
          secret:
            secretName: user
#        - name: config
#          configMap:
#            name: user
      serviceAccountName: api-service-account
      restartPolicy: Always
  strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
  minReadySeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    app: user
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: user
  type: NodePort